name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./compile.sh
      - name: Move
        run: mkdir -p build && mv ./main.pdf ./build/
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: ./build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: build
          force_orphan: true
