on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex -synctex=1 -interaction=nonstopmode main.tex
            bibtex main
            pdflatex -synctex=1 -interaction=nonstopmode main.tex
            pdflatex -synctex=1 -interaction=nonstopmode main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
            
